# Logistic regression

In [35]:
import torch
import torch.optim as optim

In [36]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0],[0], [0], [1], [1], [1]]

In [37]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [38]:
W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros((1), requires_grad = True)

In [39]:
optimizer  = optim.SGD([W,b], lr=1)

In [40]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis = 1 / (1+torch.exp(-(x_train.matmul(W)+b))) 
    # =torch.sigmoid(x_train.matmul(W)+b)
    cost = F.binary_cross_entropy(hypothesis,y_train)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 ==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


### Evaluation

In [41]:
hypothesis = torch.sigmoid(x_train.matmul(W)+b)
print(hypothesis[:5])
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5])
print(y_train[:5])
correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01]], grad_fn=<SliceBackward>)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])
tensor([[True],
        [True],
        [True],
        [True],
        [True]])


### Check functions

In [42]:
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
torch.Size([6, 2])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
torch.Size([6, 1])


In [43]:
print('e^1 equals: ', torch.exp(torch.FloatTensor([[1,2],[3,4]])))

e^1 equals:  tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])


In [44]:
print(hypothesis)
print(hypothesis.shape)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])


In [45]:
hypothesis = torch.sigmoid(x_train.matmul(W)+b)
print(hypothesis)
print(hypothesis.shape)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])
