In [ ]:
# Manipulation_2

In [16]:
import numpy as np
import torch

In [ ]:
# View(reshpae)

In [9]:
t = np.array([[[0,1,2],
              [3,4,5]],
             
             [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [12]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [15]:
print(ft.view([-1,1,3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [17]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [20]:
print(ft.squeeze(dim=1))
print(ft.squeeze(dim=1).shape)

tensor([0., 1., 2.])
torch.Size([3])
