In [1]:
# Manipulation_1

In [2]:
import numpy as np
import torch

In [3]:
### Broadcasting

In [5]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [6]:
# vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])     #3 -> [[3,3]]
print(m1 + m2)

tensor([[4., 5.]])


In [7]:
# 2 * 1 vector + 1 * 2 Vector
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [8]:
### multiplication & matrix multiplication

In [9]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print("Shape of Matrix 1: ", m1.shape)
print("Shape of Matrix 2: ", m2.shape)
print("matrix multiplication: ", m1.matmul(m2))
print("multiplication: ",        m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
matrix multiplication:  tensor([[ 5.],
        [11.]])
multiplication:  tensor([[1., 2.],
        [6., 8.]])


In [10]:
#  Mean

In [17]:
t = torch.FloatTensor([1,2])      #have to initialize by float
print(t.mean())

tensor(1.5000)


In [18]:
#Can't use mean() on integers
t = torch.LongTensor([1, 2])      #have to initialize by float
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [19]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.mean())
print(t.mean(dim=0))               #making row one       
print(t.mean(dim=1))               #making column one
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [24]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
# Sum

In [23]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [25]:
# Max and Argmax

In [26]:
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.max())                        #returns one value: max
print(t.max(dim=0))                   #returns two values: max and argmax  
print(t.max(dim=1))
print(t.max(dim=-1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
