# Manipulation_2

In [2]:
import numpy as np
import torch

### View(reshpae)

In [85]:
t = np.array([[[0,1,2],
              [3,4,5]],
             
             [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [86]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [87]:
print(ft.view([-1,1,3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze & Unsqueeze

In [88]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [89]:
print(ft.squeeze(dim=0))                    #dim=0 is row, dim=1 is column
print(ft.squeeze(dim=0).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [90]:
print(ft.squeeze(dim=1))
print(ft.squeeze(dim=1).shape)

tensor([0., 1., 2.])
torch.Size([3])


In [91]:
ft = torch.FloatTensor([0,1,2])             #ft.shape is vector because elements are 
print(ft.shape)                             # in a pair of [] not [[]].

torch.Size([3])


In [92]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [93]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)                  
# shape functions print (the number of rows. the number of columns)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [94]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [95]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type casting

In [96]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [97]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [98]:
bt = torch.ByteTensor([True, False, False, True])  #ByteTensor has boolean value
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [99]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [100]:
bt = (lt==3)                                   #Checking the element whether lt has 3
print(bt.long())

tensor([0, 0, 1, 0])


 ### Concatenate

In [101]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [102]:
print(torch.cat([x,y], dim=0))                 #(4,2)
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [103]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [104]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [105]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
# turn vector into matrix using unsqueeze function

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [106]:
print(torch.cat([x, y, z], dim=0))
# when does not use unsqueeze

tensor([1., 4., 2., 5., 3., 6.])


### Ones and zeros

In [107]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [108]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [3]:
x = torch.FloatTensor([[1,2], [3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))                               #x is changed. 
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
