# Array operations

In [ ]:
import numpy as np

### calculation

In [3]:
test_a = np.array([[1,2,3],[4,5,6]],float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [5]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
test_a * test_a                                      #element wise operation

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [13]:
matrix_a = np.arange(1,7).reshape(2,3)
matrix_b = np.arange(7,13).reshape(3,2)
matrix_a.dot(matrix_b)

array([[ 58,  64],
       [139, 154]])

### broadcasting

In [15]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [16]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [17]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [18]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [19]:
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [20]:
test_matrix // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [22]:
test_matrix **2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [3]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix+test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])