# Index

In [1]:
import numpy as np

### boolean index

In [2]:
test_array = np.array([1,4,0,2,3,8,9,7], float)

In [3]:
test_array > 3                                          #이 조건에 맞는 index 출력

array([False,  True, False, False, False,  True,  True,  True])

In [4]:
test_array[test_array>3]                                #true라고 되어있는 index의 element 출력

array([4., 8., 9., 7.])

In [5]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [6]:
A = np.arange(1,101).reshape(10,10)                     #vector A를 2dimension matrix로 변환
B = A > 67                                              #B를 boolean type으로 초기화

In [7]:
B

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [8]:
B.astype(int)                                           #B의 타입을 int형으로 변환

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### fancy index

In [9]:
a = np.array([2,4,6,8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)

In [10]:
a[b]                                                    #array b를 a에 index로 넣기

array([2., 2., 4., 8., 6., 4.])

In [11]:
a.take(b)                                               #array b를 a에 index로 넣기

array([2., 2., 4., 8., 6., 4.])

In [12]:
a = np.array([[1,4],[9,16]], float) 
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [13]:
a = np.array([[1,4],[9,16]], float)                     #matrix의 index로 vector를 쓰게되면 각각의 row를 인식
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])