# Operation in array

In [ ]:
import numpy as np

### sum function

In [7]:
test_array = np.arange(1,11)

In [9]:
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
test_array.sum(dtype=np.float)

55.0

In [15]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
test_array.sum()

78

In [12]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))