# Numpy

In [1]:
import numpy as np                             

### initializing array

In [2]:
test_array = np.array(["1", "4", 5 , 8], float)       #ndarray float형 초기화
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [4]:
test_array = np.array(["1", "4", 5 , 8], np.int32)    #ndarray 32bit int형 초기화
test_array

array([1, 4, 5, 8])

In [5]:
type(test_array[3])

numpy.int32

In [6]:
test_array.dtype

dtype('int32')

In [7]:
test_array = np.array([1,4,5,"8"],float)

In [8]:
print(test_array)

[1. 4. 5. 8.]


In [9]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [10]:
print(test_array.dtype)

float64


In [11]:
print(test_array.shape)                               #array의 shape 반환

(4,)


In [26]:
np.zeros((2,5),int)                                   #(2,5) zero matrix 생성

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])