# Comparision operation

In [ ]:
import numpy as np

### all & any

In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [12]:
sum(a>5)

4

In [4]:
np.any(a>5), np.any(a<0)

(True, False)

In [5]:
np.all(a>5), np.all(a<10)

(False, True)

### other comparation operations

In [16]:
a=np.array([1,3,0], float)
a

array([1., 3., 0.])

In [17]:
a > 0

array([ True,  True, False])

In [18]:
np.where(a>0,3,2)

array([3, 3, 2])

In [19]:
a = np.arange(5,15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.where(a>10)                                       #output index

(array([6, 7, 8, 9], dtype=int64),)

In [21]:
a = np.array([3.3, np.NaN, np.Inf],float)            #NULL값이 아닌지 맞는지 판별
np.isnan(a)

array([False,  True, False])

In [22]:
np.isfinite(a)                                       #한정된 실수인지 아닌지 판별 

array([ True, False, False])