# Concatenate

In [12]:
import numpy as np

In [13]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [18]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])

In [19]:
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])